language: python

python:
    - "3.8"

env:
    - SECRET_KEY='TEST'

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - coverage run --source=product,accounts src/zerohunger/manage.py test product accounts

after_success: coveralls



