# Generated by Django 3.0.6 on 2020-05-31 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20200528_2033'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsOrdered',
            fields=[
                (
                    'id', models.AutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')
                ),
                (
                    'quantity', models.IntegerField()),
                ('dateTimeCreated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')
                ),
                (
                    'amount_paid',
                    models.FloatField(blank=True, null=True)),
                (
                    'orderStatus',
                    models.CharField(
                        choices=[
                            ('P', 'Proccesing'),
                            ('T', 'In-Transit'),
                            ('C', 'Canceled'),
                            ('D', 'Delivered')],
                        default='P',
                        max_length=1)
                ),
                (
                    'dateAndTimeOfOrder',
                    models.DateTimeField(auto_now_add=True)),
                (
                    'amount_due',
                    models.FloatField(blank=True, null=True)),
                (
                    'has_paid',
                    models.BooleanField(default=False)
                ),
                (
                    'create_date',
                    models.DateTimeField(auto_now_add=True)
                ),
                (
                    'customer_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='customers',
                        to=settings.AUTH_USER_MODEL)
                ),
                (
                    'items_ordered',
                    models.ManyToManyField(
                        through='orders.ItemsOrdered',
                        to='product.Produce')),
            ],
        ),
        migrations.AddField(
            model_name='itemsordered',
            name='orders',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='orders.Orders'),
        ),
        migrations.AddField(
            model_name='itemsordered',
            name='produce',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='produce',
                to='product.Produce'),
        ),
    ]
