# Generated by Django 3.0.6 on 2020-06-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200608_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount_due',
            field=models.FloatField(default=2000),
            preserve_default=False,
        ),
    ]
