# Generated by Django 3.0.6 on 2020-05-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='product_img',
            field=models.CharField(
                max_length=100,
                verbose_name='Product Image'
            ),
        ),
    ]
